server:
  port: 8081

spring:
  application:
    name: ms-clientes
  datasource:
    url: jdbc:mysql://localhost:3306/prueba1?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
