<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId><artifactId>Matias_urrejola_Prueba2</artifactId><version>1.0.0</version><packaging>pom</packaging>
  <modules>
    <module>ms-clientes</module>
    <module>ms-vehiculos</module>
    <module>ms-reservas</module>
    <module>ms-pagos</module>
    <module>ms-sucursales</module>
    <module>ms-empleados</module>
    <module>ms-reportes</module>
    <module>ms-gateway</module>
    <module>ms-eureka-server</module>
  </modules>
</project>
