server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-clientes
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/clientes/**,/api/v1/direcciones/**
        - id: ms-vehiculos
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/vehiculos/**,/api/v1/categorias/**
        - id: ms-reservas
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/reservas/**,/api/v1/estados-reserva/**
        - id: ms-pagos
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/pagos/**
        - id: ms-sucursales
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/sucursales/**,/api/v1/regiones/**
        - id: ms-empleados
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/empleados/**
        - id: ms-reportes
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/reportes/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.example: DEBUG
