server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-clientes
          uri: lb://ms-clientes
          predicates:
            - Path=/api/v1/clientes/**,/api/v1/direcciones/**
        - id: ms-vehiculos
          uri: lb://ms-vehiculos
          predicates:
            - Path=/api/v1/vehiculos/**,/api/v1/categorias/**
        - id: ms-reservas
          uri: lb://ms-reservas
          predicates:
            - Path=/api/v1/reservas/**,/api/v1/estados-reserva/**
        - id: ms-pagos
          uri: lb://ms-pagos
          predicates:
            - Path=/api/v1/pagos/**
        - id: ms-sucursales
          uri: lb://ms-sucursales
          predicates:
            - Path=/api/v1/sucursales/**,/api/v1/regiones/**
        - id: ms-empleados
          uri: lb://ms-empleados
          predicates:
            - Path=/api/v1/empleados/**
        - id: ms-reportes
          uri: lb://ms-reportes
          predicates:
            - Path=/api/v1/reportes/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.example: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
